### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by lebanni** [KorDum/TotemDefender_1.7.10#7] opened 2018-06-19 01:43 UTC
If I understand correctly, the totem shoots towards the type of the filters you put in ?
So, something is going wrong :
- with the "Self filter", the totem shoots at me and enemies
- with the "Enemy Filter", the totem shoots at me and enemies
- with the "Player Filter" and "Enemy filter", the totem shoots at me and enemies
- with the "Player Filter" only, the totem stops shooting

I didn't try all the combination, but this should be enough to think that something is not working correctly.

**Comment by KorDum** [comment] 2018-06-19 06:26
Oh, old bug about which I did not know. If you don't place any upgrade, radius, damage and attack speed were 0 in fact.

Fixed in next version.
Thank you very much for testing!

**Comment by lebanni** [comment] 2018-06-19 16:10
Still not working. When I place the Enemy Filter, the totem shoot at me.

**Comment by KorDum** [comment] 2018-06-19 16:28
Can you tell me step by step? I can't reproduce the problem. Can you try break totem, place and configure it again?

**Comment by KorDum** [comment] 2018-06-19 16:42
Oops, I found code error. Fixed.
You should replace totem.

**Closed as completed by KorDum** 2018-06-19 16:42 UTC
Labels: bug

**Comment by lebanni** [comment] 2018-06-19 17:19
Just to be clear here :
- self, shoots at me
- another player, shoots at other player but me
- player, shoots at all players
- enemy, shoots at mobs (zombies, skeletons, etc.)

Am I right ?

**Comment by KorDum** [comment] 2018-06-19 17:21
Indeed.

**Comment by lebanni** [comment] 2018-06-19 17:38
It seems to work fine now. Thank you. As you can see, I really like your mod :)

**Comment by KorDum** [comment] 2018-06-19 17:52
Thanks you too!
